### ISSUE TITLE
LimitOffsetParams don't work

### ISSUE THREAD

**Issue by kamikaze** [uriyyo/fastapi-pagination#4] opened 2021-02-02 11:35 UTC
This way pagination works fine:
```python
from fastapi_pagination import pagination_params
```

When switching to limit-offset version:
```python
from fastapi_pagination.limit_offset import pagination_params
```

same code and adjusted request fail with: `"Page should be used with PaginationParams"`
Request:
```
http://0.0.0.0:8080/api/v1/call_records?date_from=2021-01-01&date_till=2021-02-01&limit=50&offset=0
```

Endpoint:
```python
@router.get('/call_records', response_model=Page[CallRecord], dependencies=[Depends(pagination_params)], tags=['calls'])
@handle_exceptions
async def get_call_records(date_from: datetime.date, date_till: datetime.date):
    records = await core.get_call_records(database, date_from, date_till, None)
    page = paginate(records)
    return page
```

**Comment by uriyyo** [comment] 2021-02-02 13:24
Can you try to use this example?

```py
from fastapi_pagination.limit_offset import pagination_params, Page
from fastapi_pagination import using_page

using_page(Page)  # set page to use

@router.get('/call_records', response_model=Page[CallRecord], dependencies=[Depends(pagination_params)], tags=['calls'])
@handle_exceptions
async def get_call_records(date_from: datetime.date, date_till: datetime.date):
    records = await core.get_call_records(database, date_from, date_till, None)
    page = paginate(records)
    return page
```

In case if you want to use another page model you must call `using_page` function with page model class.
```py
from fastapi_pagination import using_page

using_page(Page)
```

**Comment by kamikaze** [comment] 2021-02-02 14:41
Nice! Thanks, that worked! Just curious if I missed something in docs...

**Comment by uriyyo** [comment] 2021-02-02 14:47
It's my fault, I didn't add docs how to use limit-offset pagination. I will update docs, thanks for a issue)

**Comment by uriyyo** [comment] 2021-02-04 09:48
I am closing this issue. I have added docs and example for `limit-offset` based pagination.

**Closed by uriyyo** 2021-02-04 09:48 UTC

**Comment by rushilsrivastava** [comment] 2021-03-09 01:19
@uriyyo I think it would be helpful to add the `using_page` method in the documentation. Also, is there any reason there is a `using_page` method, wouldn't it just be better to use the ResponseModel of the route? Happy to send a PR unless you already tried this.

**Comment by rushilsrivastava** [comment] 2021-03-11 02:32
@uriyyo Would we have to use the `using_page` method to set the Page response mode that is being checked via `add_pagination`?

**Comment by uriyyo** [comment] 2021-03-11 07:59
@rushilsrivastava  No need to do anything) `add_pagination` will automatically configure your application.

You can take a look at examples. That's how you should use `fastapi-pagination` since `0.6.0` version.

**Comment by rushilsrivastava** [comment] 2021-03-11 08:06
Sorry slight typo - meant to say the `use_params` function to set the custom Params.

**Comment by uriyyo** [comment] 2021-03-11 09:08
With new implementation, every `Page` class has `Params` type associated with it.
Basically, `Page` class has `__params_type__` attribute wich is pointing to `Params` class.

For instance, how to create change default `Params`:
```py
from typing import TypeVar, Generic

from fastapi import Query

from fastapi_pagination.default import Page as BasePage, Params as BaseParams

T = TypeVar("T")


class Params(BaseParams):
    size: int = Query(500, gt=0, le=1_000, description="Page size")


class Page(BasePage[T], Generic[T]):
    __params_type__ = Params
```

**Comment by rushilsrivastava** [comment] 2021-03-12 14:02
I just implemented the same come on the latest version (0.6.1) and don't think that the Custom Params (or even default Params for that matter) is being exported to the generated OpenAPI docs. I am using the same code you have shown above.

**Comment by uriyyo** [comment] 2021-03-12 14:07
They must be exported. The idea is to have link between Page and Params. I have just double-checked and generated OpenAPI schema is correct.

Please, correct me in case if I missunderstood your answer.

**Comment by rushilsrivastava** [comment] 2021-03-12 14:25
Hmm, upon further testing it seems that the exporting keeps failing when Uvicorn reloads. Sometime, it exports to OpenAPI schema correctly and is shown on the docs, but most of the time only a few routes are exported. Despite not being exported to the schema, the route still works as expected.

Will report back with code that can reproduce the error.

**Comment by rushilsrivastava** [comment] 2021-03-12 14:31
Upgrading to the latest Uvicorn (0.13.4) fixed this problem for me - thanks for the help!

**Comment by uriyyo** [comment] 2021-03-12 14:39
Your welcome, happy to hear that)
