### ISSUE TITLE
pagination of records with datetimes does not include timezone (UTC) Z letter

### ISSUE THREAD

**Issue by stealthrabbi** [uriyyo/fastapi-pagination#481] opened 2022-12-21 17:24 UTC
My DB stores "datetime without timezone". When I do a query without the pagination librayr and serialize to pydantic models via `parse_obj_as`, the daettime string generated includes `Z` at the end. If I use the same query but use `paginate(session, query)`, the paged results do not specify a timezone at the end.

I'm on fastapi-pagination v0.9.1

**Comment by uriyyo** [comment] 2022-12-21 17:26
Hi @stealthrabbi,

Could you please provide a code example? So I can run it locally and debug it.

**Comment by stealthrabbi** [comment] 2022-12-21 17:31
Sorry, it is difficult to provide a sanitized example at the moment.

**Comment by stealthrabbi** [comment] 2022-12-21 18:05
I created a custom encoder in my base pydantic model. I can see it firing for API methods that are not using pagination, but it does not execute for the pagination queries:


``` python
def convert_datetime_to_iso_8601_with_z_suffix(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


class BaseSchema(BaseDataModel):
    class Config(BaseDataModel.Config):
        orm_mode = True
        use_enum_values = False

        json_encoders = {
            # custom output conversion for datetime
            datetime: convert_datetime_to_iso_8601_with_z_suffix
        }

```

**Comment by uriyyo** [comment] 2022-12-21 18:08
It would be great if you could provide a fully working minimal example that I can run to see this issue. Sorry, but I need more information. For instance, I need to see what the query that you run looks like.

**Comment by stealthrabbi** [comment] 2022-12-21 18:10
I understand. But even without that, it looks like the library isn't is using `json_encoders` set in a base model, but is using something else. I put print statemetns in the encoder method, and they're only being hit in my methods that are not using the pagination function.

Is there something in the library that is using a custom json_encoder ? Can I customize the encoder that the library uses?

**Comment by uriyyo** [comment] 2022-12-21 19:21
I think I know where the problem is.

Could you please add the following code to your project?
```py

from fastapi_pagination import Page
from datetime import datetime


def convert_datetime_to_iso_8601_with_z_suffix(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


Page.__config__.json_encoders = {
    datetime: convert_datetime_to_iso_8601_with_z_suffix
}
```

**Comment by stealthrabbi** [comment] 2022-12-21 19:51
So I actually created a custom Page class using one of your readmes, and serialized to that, but... this seems a lot simpler. This can just go anywhere when my program starts up?

**Comment by uriyyo** [comment] 2022-12-21 19:57
Yup, exactly 🙂

**Comment by stealthrabbi** [comment] 2022-12-21 19:58
This didn't seem to work, unfortunately. What did work for me was to create a custom page class, and then change my routes to reference this page:

``` python
class CustomPage(Page[T], Generic[T]):
    total: int
    page: conint(ge=1)  # type: ignore
    size: conint(ge=1)  # type: ignore
    items: Sequence[T]

    __params_type__ = Params  # Set params related to Page

    class Config(BaseConfig):
        json_encoders = {datetime.datetime: convert_datetime_to_realworld}

    @classmethod
    def create(  # type: ignore
        cls,
        items: Sequence[T],
        total: int,
        params: AbstractParams,
    ) -> AbstractPage[T]:
        if not isinstance(params, Params):
            raise ValueError("Page should be used with Params")

        return cls(
            total=total,
            items=items,
            page=params.page,
            size=params.size,
        )
        ```

**Comment by uriyyo** [comment] 2022-12-21 20:07
I guess it should be done before all route's registration processes.

This example works:
```py
from datetime import datetime
from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel

from fastapi_pagination import Page
from fastapi_pagination import paginate, add_pagination


def convert_datetime_to_iso_8601_with_z_suffix(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


Page.__config__.json_encoders = {
    datetime: convert_datetime_to_iso_8601_with_z_suffix
}

app = FastAPI()

add_pagination(app)


class MyModel(BaseModel):
    dt: datetime


@app.get("/", response_model=Page[MyModel])
async def root() -> Any:
    return paginate([MyModel(dt=datetime.now())])


if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)
```
And this example doesn't work:
```py
from datetime import datetime
from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel

from fastapi_pagination import Page
from fastapi_pagination import paginate, add_pagination


def convert_datetime_to_iso_8601_with_z_suffix(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


app = FastAPI()

add_pagination(app)


class MyModel(BaseModel):
    dt: datetime


@app.get("/", response_model=Page[MyModel])
async def root() -> Any:
    return paginate([MyModel(dt=datetime.now())])

Page.__config__.json_encoders = {
    datetime: convert_datetime_to_iso_8601_with_z_suffix
}


if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)
```

**Comment by stealthrabbi** [comment] 2022-12-21 20:38
OK great this worked, thanks so much. I had to be sure to set the encoder up before I imported anything else with fastapi that defined routes (not simply before creating the FastAPI app instance.

**Comment by uriyyo** [comment] 2022-12-21 20:42
Great, I am closing this issue. Please, reopen it, if you have more questions/issues.

**Closed by uriyyo** 2022-12-21 20:42 UTC
Labels: bug, question
