### ISSUE TITLE
Json field issues

### ISSUE THREAD

**Issue by ljbuza** [uriyyo/fastapi-pagination#316] opened 2022-05-04 12:22 UTC
Paginating output that has a field of type "Json" throws a validation error of:

```python
JSON object must be str, bytes or bytearray (type=type_error.json)
```
As a test, I changed the field type to "str"  and it will output the field values, but escaped (i.e., "{\"field\": \"value\"}").  This endpoint was properly working with the Json field type prior to implementing pagination.

Running:
Python 3.8.9
fastapi                   0.75.2
fastapi-pagination        0.9.3
pydantic                  1.9.0
SQLAlchemy                1.4.36

**Comment by uriyyo** [comment] 2022-05-05 18:06
Hi @ljbuza,

Could you please show a minimal example to reproduce this issue?

**Comment by ljbuza** [comment] 2022-05-06 05:44
```python
from fastapi import FastAPI, Depends
from fastapi_pagination import Page, add_pagination, paginate
from typing import List
from pydantic import BaseModel, Json
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy import (
    create_engine,
    VARCHAR,
    Column,
    Integer,
    String,
)
from sqlalchemy.ext.declarative import declarative_base

SQLALCHEMY_DATABASE_URL = "sqlite:///./test_app.db"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


app = FastAPI()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# models
class JobTable(Base):
    __tablename__ = "job"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=True, index=True)
    input = Column(VARCHAR, nullable=False)


Base.metadata.create_all(bind=engine)


# schemas
class Input(BaseModel):
    type: str
    val: int


class Job(BaseModel):
    name: str
    input: Input


class JobResponse(BaseModel):
    name: str
    input: Json

    class Config:
        orm_mode = True


# main routes
@app.get("/jobs", response_model=List[JobResponse])
async def get_jobs(db: Session = Depends(get_db)):
    return db_get_jobs(db=db)


@app.get("/jobs_pg", response_model=Page[JobResponse])
async def get_jobs_pg(db: Session = Depends(get_db)):
    return paginate(db_get_jobs(db=db))


@app.post("/jobs/", response_model=JobResponse)
def create_job(job: Job, db: Session = Depends(get_db)):
    return db_create_job(db=db, job=job)


# db crud
def db_create_job(db: Session, job: Job):
    new_job = JobTable(name=job.name, input=job.input.json())
    db.add(new_job)
    db.commit()
    db.refresh(new_job)
    return new_job


def db_get_jobs(db: Session):
    return db.query(JobTable).all()


def db_get_jobs_pg(db: Session):
    return db.query(JobTable)


add_pagination(app)
```

Create a couple jobs, then GET "/jobs" will work, but the paginated one, "/job_pg" will fail with the error:

```python
/python3.8/site-packages/fastapi/routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for Page[JobResponse]
response -> items -> 0 -> input
  JSON object must be str, bytes or bytearray (type=type_error.json)
```

**Comment by uriyyo** [comment] 2022-05-06 16:37
@ljbuza Looks like it's `pydantic` issue. If you change `get_jobs` endpoint to return `pydantic` model instead of `orm` model you will receive the same error:
```py
from pydantic import parse_obj_as

@app.get("/jobs", response_model=List[JobResponse])
async def get_jobs(db: Session = Depends(get_db)):
    return parse_obj_as(List[JobResponse], db_get_jobs(db=db))
```

Looks like `pydantic` doesn't allow to use valid JSON object as a value for a `Json` field, it should be always a sting-like object.

As a workaround you can define temp model and use it:
```py
from fastapi_pagination.api import set_page

class TempJsonResponse(JobResponse):
    input: str

@app.get("/jobs_pg", response_model=Page[JobResponse])
async def get_jobs_pg(db: Session = Depends(get_db)):
    with set_page(Page[TempJsonResponse]):
        return paginate(db_get_jobs(db=db))
```

**Comment by ljbuza** [comment] 2022-05-06 17:36
Thank you very much for the workaround, it'll help me to keep going with my work.

However, strangely, this works:

```python
JobResponse(name="foo", input='{"foo": "bar"}')
> JobResponse(name='foo', input={'foo': 'bar'})
```

but run it via fastapi  and it doesn't:

```python
@app.get("/jobs", response_model=List[JobResponse])
def get_jobs(db: Session = Depends(get_db)):
    return [JobResponse(name="foo", input='{"foo": "bar"}')]
```

**Comment by uriyyo** [comment] 2022-05-06 19:03
I will close this issue. Please, reopen it in case of any problems.

**Closed by uriyyo** 2022-05-06 19:03 UTC
Labels: question
